###batch-dev
server.port: 8082

server.servlet.encoding.force-response: true

spring:
  datasource:
    url: jdbc:mariadb://mariadb-dev:3306/main
    username: findear
    password: findear
    driver-class-name: org.mariadb.jdbc.Driver

    #url: jdbc:mysql://mariadb-dev:3306/batch?serverTimezone=UTC&characterEncoding=UTF-8
    #username: findear
    #password: findear
    #driver-class-name: com.mysql.cj.jdbc.Driver

  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false

logging:
  level:
    org.hibernate.SQL: debug

my:
  secret-key: Mru9QcwOF3pg6njeJk5q9Paa8qRh2tq1sJV6KBS2uC7JPiu6cCjc7VTSySPWjbXZ05mCvq25ZwvwQ%2BR2OEQcMg%3D%3D
  elasticsearch-port: elastic-search-dev:9200
