###batch-dev
server.port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/batch?serverTimezone=UTC&characterEncoding=UTF-8
    username: findear
    password: findear
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org.hibernate.SQL: debug
