###batch-dev
server.port: 8082

spring:
  datasource:
    # # Local
    # url: jdbc:mysql://localhost:3306/batch?serverTimezone=UTC&characterEncoding=UTF-8
    # driver-class-name: com.mysql.cj.jdbc.Driver
    # AWS
    url: jdbc:mariadb://j10a706.p.ssafy.io:3300/main
    driver-class-name: org.mariadb.jdbc.Driver
    username: findear
    password: findear

logging:
  level:
    org.hibernate.SQL: debug

my:
  secret-key: Mru9QcwOF3pg6njeJk5q9Paa8qRh2tq1sJV6KBS2uC7JPiu6cCjc7VTSySPWjbXZ05mCvq25ZwvwQ%2BR2OEQcMg%3D%3D
  elasticsearch-port: j10a706.p.ssafy.io:3301

