
###main-dev
server.port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hak?serverTimezone=UTC&characterEncoding=UTF-8
    username: hak
    password: hak
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug
