###main-dev
server.port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/main?serverTimezone=UTC&characterEncoding=UTF-8
    username: findear
    password: findear
    driver-class-name: com.mysql.cj.jdbc.Driver


  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
    open-in-view: false

  data:
    redis:
      host: redis-dev
      port: j10a706.p.ssafy.io:3303

logging:
  level:
    org.hibernate.SQL: debug
