###main-dev
server.port: 8080

spring:
  datasource:
    url: jdbc:mariadb://mariadb-dev:3306/main
    username: findear
    password: findear
    driver-class-name: org.mariadb.jdbc.Driver

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
    open-in-view: false
    
  data:
    redis:
      host: redis-dev
      port: 6379

logging:
  level:
    org.hibernate.SQL: debug

jwt-secret: 357638792F423F4428472B4B6250655368566D597133743677397A2443264629
jwt-duration: 7200000 # 2시간
