###main-dev
server.port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/findear?serverTimezone=UTC&characterEncoding=UTF-8
    # url: jdbc:mariadb://j10a706.p.ssafy.io:3300/main # AWS DB
    username: findear
    password: findear
    driver-class-name: com.mysql.cj.jdbc.Driver
    # driver-class-name: org.mariadb.jdbc.Driver

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
    open-in-view: false
    
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.hibernate.SQL: debug
