###main-dev
server.port: 8080

spring:
  datasource:
    # url: jdbc:mysql://localhost:3306/findear?serverTimezone=UTC&characterEncoding=UTF-8
    url: jdbc:mariadb://j10a706.p.ssafy.io:3300/main # AWS DB
    username: findear
    password: findear
    # driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: org.mariadb.jdbc.Driver

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true # 쿼리 로그 포맷팅
    open-in-view: false
    
  data:
    redis:
      host: j10a706.p.ssafy.io
      port: 3303

logging:
  level:
    org.hibernate.SQL: debug

jwt-secret: 357638792F423F4428472B4B6250655368566D597133743677397A2443264629
jwt-duration: 86400000 # 개발용 / 24시간
